create type "public"."article_category" as enum ('moule_rouge', 'moule_bleu', 'moule_noir', 'papier_spécial1', 'papier_spécial2', 'papier_spécial3', 'papier_spécial4', 'papier_spécial5', 'papier_spécial6', 'papier_spécial7');

revoke delete on table "public"."deliveryman" from "anon";

revoke insert on table "public"."deliveryman" from "anon";

revoke references on table "public"."deliveryman" from "anon";

revoke select on table "public"."deliveryman" from "anon";

revoke trigger on table "public"."deliveryman" from "anon";

revoke truncate on table "public"."deliveryman" from "anon";

revoke update on table "public"."deliveryman" from "anon";

revoke delete on table "public"."deliveryman" from "authenticated";

revoke insert on table "public"."deliveryman" from "authenticated";

revoke references on table "public"."deliveryman" from "authenticated";

revoke select on table "public"."deliveryman" from "authenticated";

revoke trigger on table "public"."deliveryman" from "authenticated";

revoke truncate on table "public"."deliveryman" from "authenticated";

revoke update on table "public"."deliveryman" from "authenticated";

revoke delete on table "public"."deliveryman" from "service_role";

revoke insert on table "public"."deliveryman" from "service_role";

revoke references on table "public"."deliveryman" from "service_role";

revoke select on table "public"."deliveryman" from "service_role";

revoke trigger on table "public"."deliveryman" from "service_role";

revoke truncate on table "public"."deliveryman" from "service_role";

revoke update on table "public"."deliveryman" from "service_role";

alter table "public"."deliveryman" drop constraint "deliveryman_id_key";

alter table "public"."deliveryman" drop constraint "deliveryman_pkey";

drop index if exists "public"."deliveryman_id_key";

drop index if exists "public"."deliveryman_pkey";

drop table "public"."deliveryman";

create table "public"."article" (
    "id" bigint generated by default as identity not null,
    "categorie" article_category not null,
    "quantity" smallint,
    "description" character varying
);


create table "public"."carboard" (
    "id" bigint generated by default as identity not null,
    "id_command" bigint,
    "quantityMax" smallint,
    "description" character varying
);


create table "public"."client" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "family_name" character varying,
    "phone" smallint,
    "address" character varying
);


create table "public"."command" (
    "id" bigint generated by default as identity not null,
    "description" character varying not null,
    "delivery_address" character varying,
    "list_articles" bigint,
    "id_client" bigint
);


create table "public"."delivery" (
    "description" character varying not null,
    "id_delivery_man" bigint not null,
    "id_command" bigint not null
);


create table "public"."delivery_man" (
    "id" bigint generated by default as identity not null,
    "created_at" date not null,
    "family_name" character varying,
    "name" character varying,
    "phone_number" numeric,
    "mail" character varying
);


CREATE UNIQUE INDEX article_pkey ON public.article USING btree (id);

CREATE UNIQUE INDEX carboard_pkey ON public.carboard USING btree (id);

CREATE UNIQUE INDEX client_pkey ON public.client USING btree (id);

CREATE UNIQUE INDEX command_pkey ON public.command USING btree (id);

CREATE UNIQUE INDEX delivery_pkey ON public.delivery USING btree (id_delivery_man, id_command);

CREATE UNIQUE INDEX deliveryman_id_key ON public.delivery_man USING btree (id);

CREATE UNIQUE INDEX deliveryman_pkey ON public.delivery_man USING btree (id);

alter table "public"."article" add constraint "article_pkey" PRIMARY KEY using index "article_pkey";

alter table "public"."carboard" add constraint "carboard_pkey" PRIMARY KEY using index "carboard_pkey";

alter table "public"."client" add constraint "client_pkey" PRIMARY KEY using index "client_pkey";

alter table "public"."command" add constraint "command_pkey" PRIMARY KEY using index "command_pkey";

alter table "public"."delivery" add constraint "delivery_pkey" PRIMARY KEY using index "delivery_pkey";

alter table "public"."delivery_man" add constraint "deliveryman_pkey" PRIMARY KEY using index "deliveryman_pkey";

alter table "public"."carboard" add constraint "carboard_id_command_fkey" FOREIGN KEY (id_command) REFERENCES command(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."carboard" validate constraint "carboard_id_command_fkey";

alter table "public"."command" add constraint "command_id_client_fkey" FOREIGN KEY (id_client) REFERENCES client(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."command" validate constraint "command_id_client_fkey";

alter table "public"."command" add constraint "command_list_articles_fkey" FOREIGN KEY (list_articles) REFERENCES article(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."command" validate constraint "command_list_articles_fkey";

alter table "public"."delivery" add constraint "livraison_id_command_fkey" FOREIGN KEY (id_command) REFERENCES command(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."delivery" validate constraint "livraison_id_command_fkey";

alter table "public"."delivery" add constraint "livraison_id_delivery_man_fkey" FOREIGN KEY (id_delivery_man) REFERENCES delivery_man(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."delivery" validate constraint "livraison_id_delivery_man_fkey";

alter table "public"."delivery_man" add constraint "deliveryman_id_key" UNIQUE using index "deliveryman_id_key";

grant delete on table "public"."article" to "anon";

grant insert on table "public"."article" to "anon";

grant references on table "public"."article" to "anon";

grant select on table "public"."article" to "anon";

grant trigger on table "public"."article" to "anon";

grant truncate on table "public"."article" to "anon";

grant update on table "public"."article" to "anon";

grant delete on table "public"."article" to "authenticated";

grant insert on table "public"."article" to "authenticated";

grant references on table "public"."article" to "authenticated";

grant select on table "public"."article" to "authenticated";

grant trigger on table "public"."article" to "authenticated";

grant truncate on table "public"."article" to "authenticated";

grant update on table "public"."article" to "authenticated";

grant delete on table "public"."article" to "service_role";

grant insert on table "public"."article" to "service_role";

grant references on table "public"."article" to "service_role";

grant select on table "public"."article" to "service_role";

grant trigger on table "public"."article" to "service_role";

grant truncate on table "public"."article" to "service_role";

grant update on table "public"."article" to "service_role";

grant delete on table "public"."carboard" to "anon";

grant insert on table "public"."carboard" to "anon";

grant references on table "public"."carboard" to "anon";

grant select on table "public"."carboard" to "anon";

grant trigger on table "public"."carboard" to "anon";

grant truncate on table "public"."carboard" to "anon";

grant update on table "public"."carboard" to "anon";

grant delete on table "public"."carboard" to "authenticated";

grant insert on table "public"."carboard" to "authenticated";

grant references on table "public"."carboard" to "authenticated";

grant select on table "public"."carboard" to "authenticated";

grant trigger on table "public"."carboard" to "authenticated";

grant truncate on table "public"."carboard" to "authenticated";

grant update on table "public"."carboard" to "authenticated";

grant delete on table "public"."carboard" to "service_role";

grant insert on table "public"."carboard" to "service_role";

grant references on table "public"."carboard" to "service_role";

grant select on table "public"."carboard" to "service_role";

grant trigger on table "public"."carboard" to "service_role";

grant truncate on table "public"."carboard" to "service_role";

grant update on table "public"."carboard" to "service_role";

grant delete on table "public"."client" to "anon";

grant insert on table "public"."client" to "anon";

grant references on table "public"."client" to "anon";

grant select on table "public"."client" to "anon";

grant trigger on table "public"."client" to "anon";

grant truncate on table "public"."client" to "anon";

grant update on table "public"."client" to "anon";

grant delete on table "public"."client" to "authenticated";

grant insert on table "public"."client" to "authenticated";

grant references on table "public"."client" to "authenticated";

grant select on table "public"."client" to "authenticated";

grant trigger on table "public"."client" to "authenticated";

grant truncate on table "public"."client" to "authenticated";

grant update on table "public"."client" to "authenticated";

grant delete on table "public"."client" to "service_role";

grant insert on table "public"."client" to "service_role";

grant references on table "public"."client" to "service_role";

grant select on table "public"."client" to "service_role";

grant trigger on table "public"."client" to "service_role";

grant truncate on table "public"."client" to "service_role";

grant update on table "public"."client" to "service_role";

grant delete on table "public"."command" to "anon";

grant insert on table "public"."command" to "anon";

grant references on table "public"."command" to "anon";

grant select on table "public"."command" to "anon";

grant trigger on table "public"."command" to "anon";

grant truncate on table "public"."command" to "anon";

grant update on table "public"."command" to "anon";

grant delete on table "public"."command" to "authenticated";

grant insert on table "public"."command" to "authenticated";

grant references on table "public"."command" to "authenticated";

grant select on table "public"."command" to "authenticated";

grant trigger on table "public"."command" to "authenticated";

grant truncate on table "public"."command" to "authenticated";

grant update on table "public"."command" to "authenticated";

grant delete on table "public"."command" to "service_role";

grant insert on table "public"."command" to "service_role";

grant references on table "public"."command" to "service_role";

grant select on table "public"."command" to "service_role";

grant trigger on table "public"."command" to "service_role";

grant truncate on table "public"."command" to "service_role";

grant update on table "public"."command" to "service_role";

grant delete on table "public"."delivery" to "anon";

grant insert on table "public"."delivery" to "anon";

grant references on table "public"."delivery" to "anon";

grant select on table "public"."delivery" to "anon";

grant trigger on table "public"."delivery" to "anon";

grant truncate on table "public"."delivery" to "anon";

grant update on table "public"."delivery" to "anon";

grant delete on table "public"."delivery" to "authenticated";

grant insert on table "public"."delivery" to "authenticated";

grant references on table "public"."delivery" to "authenticated";

grant select on table "public"."delivery" to "authenticated";

grant trigger on table "public"."delivery" to "authenticated";

grant truncate on table "public"."delivery" to "authenticated";

grant update on table "public"."delivery" to "authenticated";

grant delete on table "public"."delivery" to "service_role";

grant insert on table "public"."delivery" to "service_role";

grant references on table "public"."delivery" to "service_role";

grant select on table "public"."delivery" to "service_role";

grant trigger on table "public"."delivery" to "service_role";

grant truncate on table "public"."delivery" to "service_role";

grant update on table "public"."delivery" to "service_role";

grant delete on table "public"."delivery_man" to "anon";

grant insert on table "public"."delivery_man" to "anon";

grant references on table "public"."delivery_man" to "anon";

grant select on table "public"."delivery_man" to "anon";

grant trigger on table "public"."delivery_man" to "anon";

grant truncate on table "public"."delivery_man" to "anon";

grant update on table "public"."delivery_man" to "anon";

grant delete on table "public"."delivery_man" to "authenticated";

grant insert on table "public"."delivery_man" to "authenticated";

grant references on table "public"."delivery_man" to "authenticated";

grant select on table "public"."delivery_man" to "authenticated";

grant trigger on table "public"."delivery_man" to "authenticated";

grant truncate on table "public"."delivery_man" to "authenticated";

grant update on table "public"."delivery_man" to "authenticated";

grant delete on table "public"."delivery_man" to "service_role";

grant insert on table "public"."delivery_man" to "service_role";

grant references on table "public"."delivery_man" to "service_role";

grant select on table "public"."delivery_man" to "service_role";

grant trigger on table "public"."delivery_man" to "service_role";

grant truncate on table "public"."delivery_man" to "service_role";

grant update on table "public"."delivery_man" to "service_role";


